1. 下面的输出结果是多少

```js
  const promise = new Promise((resolve, reject) => {
      console.log(1);//同步代码
      resolve();//异步代码
      console.log(2);//同步代码
  })

  promise.then(() => {//异步代码
      console.log(3);
  })
  console.log(4);//同步代码
  // 1  2  4  3
```

2. 下面Set结构，打印出的size值是多少

```js
  let s = new Set();
  s.add([1]);//加入新数组1
  s.add([1]);//加入新数组2
  console.log(s.size);//两个数组的路径不同
  // 2
```

3. 下面的代码输出结果是

```js
  const promise1 = new Promise((resolve, reject) => {
      setTimeout(() => {
          resolve('success');
      }, 1000)
  })
  const promise2 = promise1.then(() => {//promise1结束后才运行promise2
      throw new Error('error!!!');
  })

  console.log('promise1', promise1);//pending
  console.log('promise2', promise2);//pending

  setTimeout(() => {//2s后promise1完成，promise2也完成
      console.log('promise1', promise1);//resolved
      console.log('promise2', promise2);//rejected
  }, 2000)
```

4. 下面代码的运行结果是

```js
const promise = new Promise((resolve, reject) => {
    resolve('success1');//有效代码，变为已决后状态无法改变
    reject('error');//无效代码
    resolve('success2');//无效代码
})

promise
    .then((res) => {
        console.log('then: ', res);//then success1
    })
    .catch((err) => {
        console.log('catch: ', err);//未进入rejected状态，不会执行
    })
```

5. 下面的代码输出结果是多少

```js
Promise.resolve(2)
    .then((res) => {
        console.log(res);//2
        return 2;
    })
    .catch((err) => {//未进入rejected，所以catch不执行，相当于没有
        return 3;
    })
    .then((res) => {//跨过catch，直接运行该代码
        console.log(res);//2
    })
```

6. 下面的代码输出结果是多少

```js
Promise.resolve()
    .then(() => {
        return new Error('error!!!');//返回一个错误
    })
    .then((res) => {//res：得到上一个then返回的错误
        console.log('then: ', res);//打印该错误
    })
    .catch((err) => {//为进入rejected状态，catch不执行
        console.log('catch: ', err)
    })
```

7. 下面的代码输出结果是多少

```js
Promise.resolve(1)
    .then(2)//传入的参数不是函数，相当于没有该代码
    .then(Promise.resolve(3))//传入的参数不是函数，相当于没有该代码
    .then(console.log);//将window.console.log函数传入，1作为该函数的参数传入，即打印1
```